// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package querier

import (
	"time"

	"github.com/google/uuid"
)

type AccessRule struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Org struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type PhoneCode struct {
	Phone     string
	Typ       string
	Code      string
	Used      bool
	UpdatedAt time.Time
	ExpiredAt time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Phone        string
	PasswordHash string
	PasswordSalt string
	RefreshToken *string
	OrgID        uuid.UUID
	DeletedAt    *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserAccessRule struct {
	UserID uuid.UUID
	RuleID uuid.UUID
}
