// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package querier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserAccessRule(ctx context.Context, arg AddUserAccessRuleParams) error
	CreateOrg(ctx context.Context, name string) (*Org, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	GetAccessRule(ctx context.Context, name string) (*AccessRule, error)
	GetOrgInfoByOrgId(ctx context.Context, id uuid.UUID) (*Org, error)
	GetPhoneCode(ctx context.Context, arg GetPhoneCodeParams) (*PhoneCode, error)
	GetUser(ctx context.Context, phone string) (*User, error)
	GetUserAccessRuleNames(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserAccessRules(ctx context.Context, userID uuid.UUID) ([]*GetUserAccessRulesRow, error)
	IsPhoneExist(ctx context.Context, phone string) (bool, error)
	IsUsernameExist(ctx context.Context, name string) (bool, error)
	MarkPhoneCodeUsed(ctx context.Context, arg MarkPhoneCodeUsedParams) error
	RemoveUserAccessRule(ctx context.Context, arg RemoveUserAccessRuleParams) error
	UpdateOrgOwnerID(ctx context.Context, arg UpdateOrgOwnerIDParams) error
	UpdateUserPasswordByPhone(ctx context.Context, arg UpdateUserPasswordByPhoneParams) error
	UpsertPhoneCode(ctx context.Context, arg UpsertPhoneCodeParams) (*PhoneCode, error)
}

var _ Querier = (*Queries)(nil)
