// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/xich-dev/go-starter/pkg/apps/server"
	"github.com/xich-dev/go-starter/pkg/cloud/sms"
	"github.com/xich-dev/go-starter/pkg/config"
	"github.com/xich-dev/go-starter/pkg/controller"
	"github.com/xich-dev/go-starter/pkg/middleware"
	"github.com/xich-dev/go-starter/pkg/model"
	"github.com/xich-dev/go-starter/pkg/service"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	modelInterface, err := model.NewModel(configConfig)
	if err != nil {
		return nil, err
	}
	smsManagerInterface := sms.NewSMSManager(configConfig)
	serviceInterface := service.NewService(configConfig, modelInterface, smsManagerInterface)
	middlewareMiddleware, err := middleware.NewMiddleware(configConfig)
	if err != nil {
		return nil, err
	}
	controllerController := controller.NewController(serviceInterface, middlewareMiddleware)
	serverServer := server.NewServer(configConfig, controllerController, middlewareMiddleware)
	return serverServer, nil
}
